clone_depth: 10

version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cd ..

build:
  project: build/decaf-emu.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: 7z a decaf-bin.zip build\obj\Release\decaf-sdl.exe build\obj\Release\decaf-cli.exe build\obj\Release\pm4-replay.exe build\obj\Release\zlib1.dll build\obj\Release\glbinding.dll build\obj\Release\SDL2.dll

artifacts:
  - path: decaf-bin.zip
    name: decaf-bin
