clone_depth: 10

version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x64

environment:
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6.6"
  PYTHON_ARCH: "64"
  VULKAN_SDK: "C:\\VulkanSDK\\1.1.101.0"

configuration:
  - Release

cache:
  - C:\Users\appveyor\.conan -> conanfile.py
  - '%LOCALAPPDATA%\pip\cache'

install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan & exit 0
  - cmd: appveyor DownloadFile https://sdk.lunarg.com/sdk/download/1.1.101.0/windows/VulkanSDK-1.1.101.0-Installer.exe?u= -FileName vulkan-sdk.exe
  - cmd: vulkan-sdk.exe /S
  - cmd: git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - conan install .. --build=missing -o silent=True
  - cmake -G "Visual Studio 15 2017 Win64" -DDECAF_ENABLE_LTCG=OFF -DDECAF_BUILD_TOOLS=ON -DDECAF_FFMPEG=ON -DDECAF_VULKAN=ON -DDECAF_QT=ON -DQt5Widgets_DIR=C:/Qt/5.12/msvc2017_64/lib/cmake/Qt5Widgets -DQt5Svg_DIR=C:/Qt/5.12/msvc2017_64/lib/cmake/Qt5Svg ..
  - cd ..

build:
  project: build/decaf-emu.sln
  parallel: true
  verbosity: minimal

after_build:
  - cd build\obj\Release
  - C:/Qt/5.12/msvc2017_64/bin/windeployqt.exe --release --no-translations --no-angle --no-opengl-sw decaf-qt.exe
  - 7z a decaf-bin.zip
      "*.exe"
      "*.dll"
      "resources\*"
      "iconengines\*"
      "imageformats\*"
      "platforms\*"
      "styles\*"

artifacts:
  - path: build\obj\Release\decaf-bin.zip
    name: decaf-bin
